[package]
name = "mh-tsptw"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.51"
csv = "1.4.0"
ordered-float = "5.1.0"
rand = "0.9.2"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
